experiments:

  # double_check:
  #   - "answer_one_at_a_time"
  #   - "double_check"

  # confidence_assessment:
  #   - "confidence_assessment"
    
  # answer_all:
  #   - "answer_all"

  # one_at_a_time:
  #   - "answer_one_at_a_time"

  ar_full:
    - "gold_label"
    - "plan_ar"
    - "write_ar"

  # standard:
  #   - "gold_label"
  #   - ""


  

  
